# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: gradle:alpine
variables:
  RAILWAY_SERVICE_NAME: banksoumya
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  JAVA_VERSION: 21
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  TOMCAT_URL: http://192.168.0.109:8085/manager/text
  TOMCAT_USER: "$admin"
  TOMCAT_PASS: "$admin"
  WAR_FILE: build/libs/bank-1.war
  CS_IMAGE: "registry.gitlab.com/soumya1144029/bank:latest"
cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
  - ".gradle"
  - build
stages:
- build
- test
- postman_test
- deploy
build:
  stage: build
  script:
  - gradle --version
  - gradle --build-cache assemble
  - docker build -t registry.gitlab.com/soumya1144029/bank:latest .
  - docker push registry.gitlab.com/soumya1144029/bank:latest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - ".gradle"
    - build
test:
  stage: test
  script:
  - gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - ".gradle"
    - build
postman_tests:
  stage: postman_test
  image: postman/newman:latest
  script:
  - newman run bankcollectionprod.postman_collection.json -r cli,json --reporter-json-export
    newman/report.json
  artifacts:
    paths:
    - newman/report.json
deploy-railway:
  stage: deploy
  image: ubuntu
  only:
  - pushes
  - main
  script:
  - apt-get update && apt-get install -y curl
  - curl -fsSL https://railway.app/install.sh | sh
  - railway up --service=$RAILWAY_SERVICE_NAME -d
include:
- template: Jobs/Container-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
sast:
  stage: test
