# Use the official Gradle image
image: gradle:alpine

# Define global variables and caching settings
variables:
  RAILWAY_SERVICE_NAME: "banksoumya"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  JAVA_VERSION: 21
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" # Disable Gradle daemon to avoid issues in CI
  TOMCAT_URL: "http://192.168.0.109:8085/manager/text"
  TOMCAT_USER: "$admin" # Load from GitLab CI/CD variables
  TOMCAT_PASS: "$admin" # Load from GitLab CI/CD variables
  WAR_FILE: "build/libs/bank-1.war" # Update path if necessary

# Cache settings to speed up builds
cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle
    - build

# Define the stages of the pipeline
stages:
  - build
  - test
  - security
  - postman_test
  - deploy
  - cleanup

# Build stage
build:
  stage: build
  script:
    - gradle --version
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
      - build

# Test stage
test:
  stage: test
  script:
    - gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
      - build

# Security scan stage
security:
  stage: security
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache curl
    - curl -sSL https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.33.0_linux_amd64.tar.gz | tar xz -C /usr/local/bin
    - trivy fs --exit-code 1 --no-progress . # Adjust with your security scanning command

# Postman Test stage
postman_tests:
  stage: postman_test
  image: postman/newman:latest
  script:
    - newman run bankcollectionprod.postman_collection.json -r cli,json --reporter-json-export newman/report.json
  artifacts:
    paths:
      - newman/report.json

# Deploy to Railway
deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - pushes
    - main
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d

# Cleanup stage
cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up temporary files..."
    - rm -rf build/tmp # Replace with your actual cleanup commands
