# Use the official Gradle image
image: gradle:alpine

# Define global variables and caching settings
variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  JAVA_VERSION: 21
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" # Disable Gradle daemon to avoid issues in CI

# Cache settings to speed up builds
cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle
    - build

# Define the stages of the pipeline
stages:
  - build
  - test

# Build stage
build:
  stage: build
  script:
    - gradle --version
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
      - build

# Test stage
test:
  stage: test
  script:
    - gradle check

  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
      - build