# .gitlab-ci.yml

# Use the official Gradle image for the build stage
image: gradle:alpine

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  JAVA_VERSION: 21
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" # Disable Gradle daemon to avoid issues in CI

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle
    - build

stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle --version
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
      - build

test:
  stage: test
  image: ruby:alpine # Use Ruby image for testing
  script:
    - apk add --no-cache ruby-dev
    - gem install bundler
    - bundle install
    - bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
