image: gradle:alpine

variables:
  RAILWAY_SERVICE_NAME: "banksoumya"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  JAVA_VERSION: 21
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  TOMCAT_URL: "http://192.168.0.109:8085/manager/text"
  TOMCAT_USER: "${CI_DEPLOY_USER}"
  TOMCAT_PASS: "${CI_DEPLOY_PASSWORD}"
  WAR_FILE: "build/libs/bank-1.war"
  DAST_WEBSITE: https://staging.example.com

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle
    - build

stages:
  - build
  - test
  - postman_test
  - docker_build
  - deploy
  - dast

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Security/Dast.gitlab-ci.yml

build:
  stage: build
  script:
    - gradle --version
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
      - build

test:
  stage: test
  script:
    - gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
      - build

postman_tests:
  stage: postman_test
  image: postman/newman:latest
  script:
    - newman run bankcollectionprod.postman_collection.json -r cli,json --reporter-json-export newman/report.json
  artifacts:
    paths:
      - newman/report.json

docker-build:
  stage: docker_build
  image: docker:20.10.7
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/soumya1144029/bank/main:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/soumya1144029/bank/main:$CI_COMMIT_SHA
  only:
    - main

deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - pushes
    - main
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d
