# Base image for running Gradle tasks
image: docker:20.10.16

# Docker-In-Docker (DinD) service for running Docker commands
services:
  - docker:20.10.16-dind

variables:
  RAILWAY_SERVICE_NAME: banksoumya
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  JAVA_VERSION: 21
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  TOMCAT_URL: http://192.168.0.109:8085/manager/text
  TOMCAT_USER: "admin"
  TOMCAT_PASS: "admin"
  WAR_FILE: build/libs/bank-1.war
  CS_IMAGE: "registry.gitlab.com/soumya1144029/bank:latest"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# Cache Gradle dependencies and build output
cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - ".gradle"
    - "build"

stages:
  - build
  - test
  - postman_test
  - deploy

# Build stage
build:
  stage: build
  script:
    - apk add --no-cache curl jq openjdk11 # Install necessary tools and Java
    - curl -LO "https://services.gradle.org/distributions/gradle-8.10-bin.zip"
    - unzip gradle-8.10-bin.zip
    - export PATH=$PATH:./gradle-8.10/bin
    - gradle --version
    - gradle --build-cache assemble
    - docker build -t registry.gitlab.com/soumya1144029/bank:latest .
    - docker push registry.gitlab.com/soumya1144029/bank:latest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - ".gradle"
      - "build"

# Test stage
test:
  stage: test
  script:
    - gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - ".gradle"
      - "build"

# Postman tests stage
postman_tests:
  stage: postman_test
  image: postman/newman:latest
  script:
    - newman run bankcollectionprod.postman_collection.json -r cli,json --reporter-json-export newman/report.json
  artifacts:
    paths:
      - newman/report.json

# Deployment to Railway stage
deploy-railway:
  stage: deploy
  image: ubuntu:latest
  only:
    - pushes
    - main
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d

# Include security and container scanning templates
include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

sast:
  stage: test
