//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.05 at 11:19:03 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://example.com/loan", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.BankingApplicationForSoumya.webservice;
